# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Analytic(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'str',
        'context_description': 'str',
        'context_name': 'str',
        'total_count': 'float',
        'unique_count': 'float'
    }

    attribute_map = {
        'context': 'Context',
        'context_description': 'ContextDescription',
        'context_name': 'ContextName',
        'total_count': 'TotalCount',
        'unique_count': 'UniqueCount'
    }

    def __init__(self, context=None, context_description=None, context_name=None, total_count=None, unique_count=None):
        """
        Analytic - a model defined in Swagger
        """

        self._context = None
        self._context_description = None
        self._context_name = None
        self._total_count = None
        self._unique_count = None

        if context is not None:
          self.context = context
        if context_description is not None:
          self.context_description = context_description
        if context_name is not None:
          self.context_name = context_name
        if total_count is not None:
          self.total_count = total_count
        if unique_count is not None:
          self.unique_count = unique_count

    @property
    def context(self):
        """
        Gets the context of this Analytic.
        

        :return: The context of this Analytic.
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """
        Sets the context of this Analytic.
        

        :param context: The context of this Analytic.
        :type: str
        """

        self._context = context

    @property
    def context_description(self):
        """
        Gets the context_description of this Analytic.
        

        :return: The context_description of this Analytic.
        :rtype: str
        """
        return self._context_description

    @context_description.setter
    def context_description(self, context_description):
        """
        Sets the context_description of this Analytic.
        

        :param context_description: The context_description of this Analytic.
        :type: str
        """

        self._context_description = context_description

    @property
    def context_name(self):
        """
        Gets the context_name of this Analytic.
        

        :return: The context_name of this Analytic.
        :rtype: str
        """
        return self._context_name

    @context_name.setter
    def context_name(self, context_name):
        """
        Sets the context_name of this Analytic.
        

        :param context_name: The context_name of this Analytic.
        :type: str
        """

        self._context_name = context_name

    @property
    def total_count(self):
        """
        Gets the total_count of this Analytic.
        

        :return: The total_count of this Analytic.
        :rtype: float
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """
        Sets the total_count of this Analytic.
        

        :param total_count: The total_count of this Analytic.
        :type: float
        """

        self._total_count = total_count

    @property
    def unique_count(self):
        """
        Gets the unique_count of this Analytic.
        

        :return: The unique_count of this Analytic.
        :rtype: float
        """
        return self._unique_count

    @unique_count.setter
    def unique_count(self, unique_count):
        """
        Sets the unique_count of this Analytic.
        

        :param unique_count: The unique_count of this Analytic.
        :type: float
        """

        self._unique_count = unique_count

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Analytic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
