# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CreatingANewSegmentRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'match_type': 'str'
    }

    attribute_map = {
        'name': 'Name',
        'match_type': 'MatchType'
    }

    def __init__(self, name=None, match_type=None):
        """
        CreatingANewSegmentRequest - a model defined in Swagger
        """

        self._name = None
        self._match_type = None

        self.name = name
        if match_type is not None:
          self.match_type = match_type

    @property
    def name(self):
        """
        Gets the name of this CreatingANewSegmentRequest.
        The name of the segment.

        :return: The name of this CreatingANewSegmentRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreatingANewSegmentRequest.
        The name of the segment.

        :param name: The name of this CreatingANewSegmentRequest.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def match_type(self):
        """
        Gets the match_type of this CreatingANewSegmentRequest.
        Specifies how the segment's criteria will match together. This must be one of the following values. If not specified, `All` will be assumed.

        :return: The match_type of this CreatingANewSegmentRequest.
        :rtype: str
        """
        return self._match_type

    @match_type.setter
    def match_type(self, match_type):
        """
        Sets the match_type of this CreatingANewSegmentRequest.
        Specifies how the segment's criteria will match together. This must be one of the following values. If not specified, `All` will be assumed.

        :param match_type: The match_type of this CreatingANewSegmentRequest.
        :type: str
        """

        self._match_type = match_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreatingANewSegmentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
