# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Context110(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'analytics': 'list[Analytic]',
        'paging': 'Paging'
    }

    attribute_map = {
        'analytics': 'Analytics',
        'paging': 'Paging'
    }

    def __init__(self, analytics=None, paging=None):
        """
        Context110 - a model defined in Swagger
        """

        self._analytics = None
        self._paging = None

        if analytics is not None:
          self.analytics = analytics
        if paging is not None:
          self.paging = paging

    @property
    def analytics(self):
        """
        Gets the analytics of this Context110.
        

        :return: The analytics of this Context110.
        :rtype: list[Analytic]
        """
        return self._analytics

    @analytics.setter
    def analytics(self, analytics):
        """
        Sets the analytics of this Context110.
        

        :param analytics: The analytics of this Context110.
        :type: list[Analytic]
        """

        self._analytics = analytics

    @property
    def paging(self):
        """
        Gets the paging of this Context110.

        :return: The paging of this Context110.
        :rtype: Paging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """
        Sets the paging of this Context110.

        :param paging: The paging of this Context110.
        :type: Paging
        """

        self._paging = paging

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Context110):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
