# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Context72(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'campaigns': 'list[Campaign]',
        'paging': 'Paging76'
    }

    attribute_map = {
        'campaigns': 'Campaigns',
        'paging': 'Paging'
    }

    def __init__(self, campaigns=None, paging=None):
        """
        Context72 - a model defined in Swagger
        """

        self._campaigns = None
        self._paging = None

        if campaigns is not None:
          self.campaigns = campaigns
        if paging is not None:
          self.paging = paging

    @property
    def campaigns(self):
        """
        Gets the campaigns of this Context72.
        

        :return: The campaigns of this Context72.
        :rtype: list[Campaign]
        """
        return self._campaigns

    @campaigns.setter
    def campaigns(self, campaigns):
        """
        Sets the campaigns of this Context72.
        

        :param campaigns: The campaigns of this Context72.
        :type: list[Campaign]
        """

        self._campaigns = campaigns

    @property
    def paging(self):
        """
        Gets the paging of this Context72.

        :return: The paging of this Context72.
        :rtype: Paging76
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """
        Sets the paging of this Context72.

        :param paging: The paging of this Context72.
        :type: Paging76
        """

        self._paging = paging

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Context72):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
