# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Context32(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'paging': 'Paging',
        'subscribers': 'list[Subscriber]'
    }

    attribute_map = {
        'paging': 'Paging',
        'subscribers': 'Subscribers'
    }

    def __init__(self, paging=None, subscribers=None):
        """
        Context32 - a model defined in Swagger
        """

        self._paging = None
        self._subscribers = None

        if paging is not None:
          self.paging = paging
        if subscribers is not None:
          self.subscribers = subscribers

    @property
    def paging(self):
        """
        Gets the paging of this Context32.

        :return: The paging of this Context32.
        :rtype: Paging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """
        Sets the paging of this Context32.

        :param paging: The paging of this Context32.
        :type: Paging
        """

        self._paging = paging

    @property
    def subscribers(self):
        """
        Gets the subscribers of this Context32.
        

        :return: The subscribers of this Context32.
        :rtype: list[Subscriber]
        """
        return self._subscribers

    @subscribers.setter
    def subscribers(self, subscribers):
        """
        Sets the subscribers of this Context32.
        

        :param subscribers: The subscribers of this Context32.
        :type: list[Subscriber]
        """

        self._subscribers = subscribers

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Context32):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
