# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Context132(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'a': 'A',
        'b': 'B',
        'campaign_id': 'str'
    }

    attribute_map = {
        'a': 'A',
        'b': 'B',
        'campaign_id': 'CampaignID'
    }

    def __init__(self, a=None, b=None, campaign_id=None):
        """
        Context132 - a model defined in Swagger
        """

        self._a = None
        self._b = None
        self._campaign_id = None

        if a is not None:
          self.a = a
        if b is not None:
          self.b = b
        if campaign_id is not None:
          self.campaign_id = campaign_id

    @property
    def a(self):
        """
        Gets the a of this Context132.

        :return: The a of this Context132.
        :rtype: A
        """
        return self._a

    @a.setter
    def a(self, a):
        """
        Sets the a of this Context132.

        :param a: The a of this Context132.
        :type: A
        """

        self._a = a

    @property
    def b(self):
        """
        Gets the b of this Context132.

        :return: The b of this Context132.
        :rtype: B
        """
        return self._b

    @b.setter
    def b(self, b):
        """
        Sets the b of this Context132.

        :param b: The b of this Context132.
        :type: B
        """

        self._b = b

    @property
    def campaign_id(self):
        """
        Gets the campaign_id of this Context132.
        

        :return: The campaign_id of this Context132.
        :rtype: str
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id):
        """
        Sets the campaign_id of this Context132.
        

        :param campaign_id: The campaign_id of this Context132.
        :type: str
        """

        self._campaign_id = campaign_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Context132):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
