# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CustomField(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom_field_id': 'str',
        'name': 'str',
        'value': 'str'
    }

    attribute_map = {
        'custom_field_id': 'CustomFieldID',
        'name': 'Name',
        'value': 'Value'
    }

    def __init__(self, custom_field_id=None, name=None, value=None):
        """
        CustomField - a model defined in Swagger
        """

        self._custom_field_id = None
        self._name = None
        self._value = None

        if custom_field_id is not None:
          self.custom_field_id = custom_field_id
        if name is not None:
          self.name = name
        if value is not None:
          self.value = value

    @property
    def custom_field_id(self):
        """
        Gets the custom_field_id of this CustomField.
        

        :return: The custom_field_id of this CustomField.
        :rtype: str
        """
        return self._custom_field_id

    @custom_field_id.setter
    def custom_field_id(self, custom_field_id):
        """
        Sets the custom_field_id of this CustomField.
        

        :param custom_field_id: The custom_field_id of this CustomField.
        :type: str
        """

        self._custom_field_id = custom_field_id

    @property
    def name(self):
        """
        Gets the name of this CustomField.
        

        :return: The name of this CustomField.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CustomField.
        

        :param name: The name of this CustomField.
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """
        Gets the value of this CustomField.
        

        :return: The value of this CustomField.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this CustomField.
        

        :param value: The value of this CustomField.
        :type: str
        """

        self._value = value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CustomField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
